### ISSUE TITLE
requires msyql

### ISSUE THREAD

**Issue by paulbhartzog** [sachin/silverspoon#1]
Love the app.
Just have a recommendation for a few things on your README.

**First**
This part should be before SETUP
and it is unclear:

> Start your application from rails5 skeleton
> To start your application from rails5 skeleton you need to export the code from rails5 skeleton repository.
> $ git archive master | tar -x -C /somewhere/else

It should state 1) do git archive, 2) cd into that dir, 3) setup db yaml, 4) proceed to next part

**Second**
Your app requires mysql or it will generate this message on a mac:
"mysql client is missing. You may need to 'brew install mysql' or 'port install mysql', and try again."
EZ to fix, but you might want to update your docs to mention the requirement. :-)

much thx :-)

**Comment by sachin** [comment]
Hey Paul B. Hartzog,

Thanks for the issues, reporting to me. Yes you raised valid points and i updated the readme file. 
I hope its more informative now.

again thanks

regards
Sachin
