### ISSUE TITLE
credentials not working?

### ISSUE THREAD

**Issue by KaraAJC** [sachin/silverspoon#3]
I used: 
email - admin@example.com 
and 
PW - Welcome@123

but got multiple password invalid errors, then finally this error: 

```
The change you wanted was rejected.

Maybe you tried to change something you didn't have access to.
```

have the admin credentials changed? I'd like to see the invite interface.

**Comment by sachin** [comment]
Hi Kara,

Thanks for reporting this to me. Actually someone deleted the admin user. I fixed it and it should works fine now. Thanks for your support. cheers :)

**Comment by Frinkiac-7** [comment]
Hi @sachin,

Not sure if someone deleted the admin account again but I'm trying to use the admin@example.com/Welcome@123 credentials and getting the same error as Kara did.  Thanks in advance for your help, mate.

Rob

**Comment by sachin** [comment]
Hi @Frinkiac-7 

Again someone alters the admin user, I fixed it. Give it a try now. cheers

**Comment by Frinkiac-7** [comment]
Many thanks, @sachin!  Great demo, mate!

**Comment by sachin** [comment]
Always welcome dear cheers :)

**Comment by sang96011** [comment]
@sachin 
I can't login by admin credential, you can reset it?

**Comment by sachin** [comment]
@sang96011 fixed. please check

**Comment by sang96011** [comment]
@sachin oke. Thank you so much!
