### ISSUE TITLE
bin/rails: exception reentered (fatal)

### ISSUE THREAD

**Issue by sfeu** [sachin/silverspoon#4]
Thanks for the example app. I installed it as described in the readme, needed to update puma, nokogiri and mysql2 to the most recent version and got the following errors:

rails db:create db:migrate db:seed
Created database 'skeleton_development'
Created database 'skeleton_test'
bin/rails: exception reentered (fatal)

rails s
=> Booting Puma
=> Rails 5.0.0.1 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
Exiting
bin/rails: exception reentered (fatal)

Anyone has an idea where to start debugging?

Thanks

**Comment by sachin** [comment]
Thanks for reporting this, I will look into this and update you

**Comment by sachin** [comment]
It was due to active admin gem. Which tries to load the patron table before running the migration.
[more info](https://github.com/hzamani/acts_as_relation/issues/71)
[fixed](https://github.com/sachin/silverspoon/commit/4866fc46e01300962628a1f30bfd29ae8aa8f7fc)
