### ISSUE TITLE
uninitialized constant User::InvitedBy

### ISSUE THREAD

**Issue by kart-able** [sachin/silverspoon#5]
This app is promising. The only issue I've had after install is in trying to get users from the top menu:

> NameError in Admin::Users#index
> Showing C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-ee49d3d2d13c/app/views/active_admin/resource/index.html.arb where line #2 raised:
> Extracted source (around line #152):
> raise NameError.new("uninitialized constant #{candidates.first}", candidates.first)

I am sorry I can't help.

**Comment by sachin** [comment]
Thanks for reporting fixed. [commit](https://github.com/sachin/silverspoon/commit/ce07a1f364c012c40ea2f450255607f50849f733)
